name: Build and deploy pollen site

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.9.1
        with:
          node-version: 24
      - uses: Bogdanp/setup-racket@v1.10
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
      - name: Build pollen files to ../pyret.org.published
        run: |
          raco pkg install --deps search-auto pollen
          npm install
          mkdir -p . ../pyret.org.published
          raco pollen publish . ../pyret.org.published
      - name: Build documentation
        run: |
          mkdir -p ../pyret.org.published/docs

          git clone --branch master https://github.com/brownplt/pyret-docs latest-docs
          pushd latest-docs; npm install; make; popd
          cp -r latest-docs/build/docs ../pyret.org.published/docs/latest

          git clone --branch horizon https://github.com/brownplt/pyret-docs horizon-docs
          pushd horizon-docs; npm install; make; popd
          cp -r horizon-docs/build/docs ../pyret.org.published/docs/horizon

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ../pyret.org.published
  
  deploy:
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
